version: '3'

services:
  postgres:
    image: postgres:14.5
    hostname: postgres
    env_file:
      - pgsql-variables.env
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - tbot-network

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    hostname: web
    command: python bot.py
    env_file:
      - ./.env
    volumes:
      - ..:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - tbot-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ..:/usr/src/app
    depends_on:
      - web
    networks:
      - tbot-network

volumes:
  pgdata:

networks:
  tbot-network: